typography_spectrum: 0.25637
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0876403187867254
  lightness: 0.2961779406759888
  saturation: 0.5
  rhythmicContrast: 0.15659635374322534
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24579
analytics:
  google: null
  facebook: null
  twitter: null
name: Resor
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Resor
description: 'Hemma bra, men borta bäst'
purpose: []
